name: Build script update

on:
  schedule:
    - cron:  '30 5 * * *'
  workflow_dispatch:

jobs:
  update-build-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Update build script
        run: |
          java -jar simpleupdater.jar -Rnekit508/mindustry-mod-template
      - name: Update repository
        uses: EndBug/add-and-commit@v9
        with:
          message: Build script update