name: Testing

on: [push, pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20
      - name: Build mod jars
        run: |
          chmod +x gradlew
          ./gradlew copyBuildRelease --stacktrace
      - name: Get mod version
        id: get-version
        run: |
          VERSION=$(cat mod.json | jq -r '.version')
          echo "::set-output name=version::$VERSION"
      - name: Rename jar
        run: |
          mv artifacts/Sueno.jar artifacts/Sueno-${{ steps.get-version.outputs.version }}-${{ github.run_number }}.jar
      - name: Discord Webhook Action 1
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: Сборка Sueno №${{ github.run_number }}
          embed-description: "### Изменения:\n${{ github.event.commits[0].message }}"
          embed-color: 15386701
          embed-url: ${{ github.event.commits[0].url }}
          embed-footer-text: Версия мода **${{ steps.get-version.outputs.version }}**
          filename: artifacts/Sueno-${{ steps.get-version.outputs.version }}-${{ github.run_number }}.jar
      - name: Upload built jar file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: artifacts/*.jar